#lang pollen

◊(define-meta title            "About Me")

Hi, I'm Faiz (pronounced ◊smallcaps{fez}). I'm a Computing major in the ◊hyperlink["https://ccs.ucsb.edu"]{College of Creative Studies} at UC Santa Barbara. At the moment, I'm based in the Netherlands, where I'm studying abroad for the next several months. This summer, I'll be working at Stanford's ◊hyperlink["https://reglab.stanford.edu/about/"]{RegLab}, where I'll be researching the application of deep learning and large language models to the legal domain.

In the field of computer science, my current interests include network analysis, scalable systems, and neural language processing. Currently, I'm focused on ◊hyperlink["/projects/lexcaliber"]{Lexcaliber}, a suite of network- and NLP-based recommendation and analyis algorithms to aid legal research. In that vein, I am an active contributor to the Free Law Project's open-source software and recently co-created ◊hyperlink["https://free.law/2022/03/17/summarizing-important-cases"]{a court opinion summarization feature} in CourtListener, a free legal research website. My other projects include ◊hyperlink["/projects/drdocx"]{DrDocx,} ◊hyperlink["https://github.com/project-anacapa/anacapa-github-linker"]{a computer science education research tool,} ◊hyperlink["https://github.com/ProbablyFaiz/TABitha"]{an automated tabulation system for mock trial tournaments,} and ◊hyperlink["https://github.com/ProbablyFaiz/worduel"]{various} ◊hyperlink["https://faizsurani.com/assets/gnp-evacuation-routes.pdf"]{other} ◊hyperlink["https://github.com/ProbablyFaiz/RedditPoliticalSentiment"]{small projects}.

Outside of computer science, I'm a dedicated effective altruist. Since 2020, I've been a member of and volunteer for ◊hyperlink["https://givingwhatwecan.org"]{Giving What We Can}, for which I work on various writing and data science projects. I'm also passionate about public policy and constitutional law. My recent writing in these areas includes articles on ◊hyperlink["https://dailynexus.com/2020-12-25/the-supreme-court-considers-reviving-state-sponsored-discrimination/"]{religious liberty}, ◊hyperlink["/assets/parable-of-unix.pdf"]{copyright}, and ◊hyperlink["/assets/affirmative-action.pdf"]{affirmative action} law. I also co-founded and led UCSB's ◊hyperlink["https://ucsbmootcourt.org"]{undergraduate moot court team}, which has won back-to-back national championships in the ◊hyperlink["https://amcamootcourt.org"]{American Moot Court Association's} appellate brief competition and placed within the top 4 in the national oral argument tournament. For an independently organized moot court tournament, I co-authored ◊hyperlink["https://ucsbmootcourt.org/stockton-v-lsr"]{◊i{Stockton v. LSR Tutoring}}, a fictional case problem centered around the Free Exercise Clause and the Americans with Disabilities Act.

If you have an interesting opportunity or good book recommendation, I'd love to ◊hyperlink["mailto:faiz@faizsurani.com"]{hear from you.}
