#lang pollen

◊(define-meta title            "About Me")

Hi, I'm Faiz (pronounced ◊smallcaps{fez}). I'm a Computing major in the ◊hyperlink["https://ccs.ucsb.edu"]{College of Creative Studies} at UC Santa Barbara. At the moment, I'm based in the Netherlands, where I'm studying abroad for the next several months.

In the field of computer science, my current interests include network analysis, scalable systems, and functional programming. Currently, I'm focused on ◊hyperlink["/projects/lexcaliber"]{Lexcaliber}, a suite of network- and NLP-based recommendation and analyis algorithms to aid legal research. My other projects include ◊hyperlink["/projects/drdocx"]{DrDocx,} ◊hyperlink["https://github.com/project-anacapa/anacapa-github-linker"]{a computer science education research tool,} ◊hyperlink["https://github.com/ProbablyFaiz/TABitha"]{an automated tabulation system for mock trial tournaments,} and ◊hyperlink["https://faizsurani.com/assets/toll-of-substance-abuse.pdf"]{various} ◊hyperlink["https://faizsurani.com/assets/gnp-evacuation-routes.pdf"]{data science} ◊hyperlink["https://github.com/ProbablyFaiz/RedditPoliticalSentiment"]{projects} among other things.

Outside of computer science, I'm passionate about effective altruism, public policy, and constitutional law. Since 2020, I've been a member of and volunteer for ◊hyperlink["https://givingwhatwecan.org"]{Giving What We Can}, for which I work on various writing and data science projects. I'm also passionate about public policy and constitutional law. My recent writing in these areas includes articles on ◊hyperlink["https://dailynexus.com/2020-12-25/the-supreme-court-considers-reviving-state-sponsored-discrimination/"]{religious liberty}, ◊hyperlink["/assets/parable-of-unix.pdf"]{copyright}, and ◊hyperlink["/assets/affirmative-action.pdf"]{affirmative action} law. I also co-founded and currently lead UCSB's ◊hyperlink["https://ucsbmootcourt.org"]{undergraduate moot court team}, which has won back-to-back national championships in the ◊hyperlink["https://amcamootcourt.org"]{American Moot Court Association's} appellate brief competition. 

This website is created with ◊hyperlink["https://github.com/mbutterick/pollen"]{Pollen,} an open-source publishing system built in Racket. As much as I'm enjoying Racket, I can't take credit for the incredible work done by Joel Dueck, whose ◊hyperlink["https://github.com/otherjoel/try-pollen"]{try-pollen} project provides much of the code powering this website.

If you have an interesting opportunity or good book recommendation, I'd love to ◊hyperlink["mailto:faiz@faizsurani.com"]{hear from you.}
