steps:
- uses: actions/checkout@master
- uses: Bogdanp/setup-racket@v1.7
  with:
    architecture: 'x64'
    distribution: 'full'
    variant: 'CS'
    version: '8.3'
- run: raco pkg install --auto pollen gregor
- run: racket hello.rkt